secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      secrets:
        - GITHUB_TOKEN
      args:
        - PRIVATE_KEY=${PRIVATE_KEY}
      target: slim-linter
    image: super_linter:latest
    container_name: compose_super_linter
    hostname: super_linter
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RMQ_DSN=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres:

networks:
  rabbit-mq:
