# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.models.project_with_scans import ProjectWithScans

class TestProjectWithScans(unittest.TestCase):
    """ProjectWithScans unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectWithScans:
        """Test ProjectWithScans
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectWithScans`
        """
        model = ProjectWithScans()
        if include_optional:
            return ProjectWithScans(
                name = '',
                repository_url = '',
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                owner_id = 56,
                scans = [
                    linter_api_client.models.scan.Scan(
                        branch = '', 
                        id = 56, 
                        project_id = 56, 
                        status = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_errors = 56, 
                        total_warnings = 56, )
                    ]
            )
        else:
            return ProjectWithScans(
                name = '',
                repository_url = '',
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                owner_id = 56,
                scans = [
                    linter_api_client.models.scan.Scan(
                        branch = '', 
                        id = 56, 
                        project_id = 56, 
                        status = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_errors = 56, 
                        total_warnings = 56, )
                    ],
        )
        """

    def testProjectWithScans(self):
        """Test ProjectWithScans"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
