# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.models.project_create import ProjectCreate

class TestProjectCreate(unittest.TestCase):
    """ProjectCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreate:
        """Test ProjectCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCreate`
        """
        model = ProjectCreate()
        if include_optional:
            return ProjectCreate(
                name = '',
                repository_url = '',
                token = ''
            )
        else:
            return ProjectCreate(
                name = '',
                repository_url = '',
                token = '',
        )
        """

    def testProjectCreate(self):
        """Test ProjectCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
