# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.models.linter_stats import LinterStats

class TestLinterStats(unittest.TestCase):
    """LinterStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinterStats:
        """Test LinterStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinterStats`
        """
        model = LinterStats()
        if include_optional:
            return LinterStats(
                linter_name = '',
                total_runs = 56,
                success_rate = 1.337,
                avg_errors = 1.337,
                avg_warnings = 1.337
            )
        else:
            return LinterStats(
                linter_name = '',
                total_runs = 56,
                success_rate = 1.337,
                avg_errors = 1.337,
                avg_warnings = 1.337,
        )
        """

    def testLinterStats(self):
        """Test LinterStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
