# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.models.scan_create import ScanCreate

class TestScanCreate(unittest.TestCase):
    """ScanCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanCreate:
        """Test ScanCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanCreate`
        """
        model = ScanCreate()
        if include_optional:
            return ScanCreate(
                branch = '',
                project_id = 56
            )
        else:
            return ScanCreate(
                branch = '',
                project_id = 56,
        )
        """

    def testScanCreate(self):
        """Test ScanCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
