# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_project_projects_post(self) -> None:
        """Test case for create_project_projects_post

        Create Project
        """
        pass

    def test_create_scan_scans_post(self) -> None:
        """Test case for create_scan_scans_post

        Create Scan
        """
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Create User
        """
        pass

    def test_get_scan_stats_linter_results_stats_scan_id_get(self) -> None:
        """Test case for get_scan_stats_linter_results_stats_scan_id_get

        Get Scan Stats
        """
        pass

    def test_ping_technical_ping_get(self) -> None:
        """Test case for ping_technical_ping_get

        Ping
        """
        pass

    def test_read_linter_results_linter_results_get(self) -> None:
        """Test case for read_linter_results_linter_results_get

        Read Linter Results
        """
        pass

    def test_read_project_projects_project_id_get(self) -> None:
        """Test case for read_project_projects_project_id_get

        Read Project
        """
        pass

    def test_read_project_scans_scans_project_project_id_get(self) -> None:
        """Test case for read_project_scans_scans_project_project_id_get

        Read Project Scans
        """
        pass

    def test_read_projects_projects_get(self) -> None:
        """Test case for read_projects_projects_get

        Read Projects
        """
        pass

    def test_read_scan_results_linter_results_scan_scan_id_get(self) -> None:
        """Test case for read_scan_results_linter_results_scan_scan_id_get

        Read Scan Results
        """
        pass

    def test_read_scan_scans_scan_id_get(self) -> None:
        """Test case for read_scan_scans_scan_id_get

        Read Scan
        """
        pass

    def test_read_scans_scans_get(self) -> None:
        """Test case for read_scans_scans_get

        Read Scans
        """
        pass

    def test_read_user_users_user_id_get(self) -> None:
        """Test case for read_user_users_user_id_get

        Read User
        """
        pass

    def test_read_users_users_get(self) -> None:
        """Test case for read_users_users_get

        Read Users
        """
        pass

    def test_ready_check_technical_ready_get(self) -> None:
        """Test case for ready_check_technical_ready_get

        Ready Check
        """
        pass

    def test_start_scan_scans_project_id_start_post(self) -> None:
        """Test case for start_scan_scans_project_id_start_post

        Start Scan
        """
        pass


if __name__ == '__main__':
    unittest.main()



def test_docker_integration(docker_client):
    container = docker_client.containers.run(
        'python:3.9-slim',
        ['python', '-c', 'print("test")'],
        remove=True
    )
    assert b'test' in container.logs()