# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.api.technical_api import TechnicalApi


class TestTechnicalApi(unittest.TestCase):
    """TechnicalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TechnicalApi()

    def tearDown(self) -> None:
        pass

    def test__technical_ping_get(self) -> None:
        """Test case for _technical_ping_get

        Ping
        """
        pass

    def test__technical_ready_get(self) -> None:
        """Test case for _technical_ready_get

        Ready Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
