# coding: utf-8

"""
    Super Linter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from linter_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test__projects_get(self) -> None:
        """Test case for _projects_get

        Read Projects
        """
        pass

    def test__projects_post(self) -> None:
        """Test case for _projects_post

        Create Project
        """
        pass

    def test__projects_project_id_get(self) -> None:
        """Test case for _projects_project_id_get

        Read Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
